name: TOC Interface Updater
description: Updates Interface versions found in World of Warcraft TOC metadata files
branding:
  icon: tag
  color: yellow
inputs:
  flavor:
    description: Interface version to default to
    default: retail
  beta:
    description: Include beta versions?
  ptr:
    description: Include PTR versions?
  depth:
    description: Recursion depth when looking for TOC files
runs:
  using: composite
  steps:
    - run: bash ${{ github.action_path }}/update.sh ${{ inputs.flavor != '' && '-f' || '' }} "${{ inputs.flavor }}" ${{ inputs.beta != '' && '-b' || '' }} ${{ inputs.ptr != '' && '-p' || '' }} ${{ inputs.depth != '' && '-d' || '' }} "${{ inputs.depth }}"
      shell: bash
